<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/fa/default.php 
 * 
 * Contao extension: BackupDB 1.5.0 stable 
 * Persian translation file 
 * 
 * Copyright : 2007-2012 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Hagen Klemp (do_while), http://www.softleister.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['backup_text'] = "پشتیبان پایگاه داده تایپولایت به صورت دانلود";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_caption'] = "شروع ساخت پشتیبان از پایگاه‌داده";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_title'] = "پشتیبان گیری اس‌کیو‌ال از پایگاه داده را ضروع می کند.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_text'] = "تنظیمات وب سایت را ذخیره می کند و برای ابزار نصب الگوی وب سایت را ایجاد می کند";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_sqltxt'] = "   ";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_caption'] = "ایجاد پوسته وب‌سایت";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_button_title'] = "شروع ایجاد پوسته وب‌سایت";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_files'] = "پرونده‌های جدید:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_module'] = "ماژول‌های زیر باید نصب شوند:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_none'] = "هیچ";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_inst'] = "نصب:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl10'] = "۱. بسته کانتائو را روی دامین خود نصب نمایید.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl11'] = "(یعنی فایل زیپ شده را باز نموده و توسط اف‌تی‌پی رو فضای وب‌سایت خود آپلود نمایید)";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl12'] = "InstallTool را حالا استفاده نکنید، اما در مرحله ۵!";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl20'] = "۲. نصب کلیه لیست افزونه‌ها.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl30'] = "۳. ذخیره الگوی وب سایت در مسیر /templates/.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl40'] = "۴. ذخیره کلیه فایل موردنیاز برای الگوی وب‌سایت در مسیر";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl41'] = "/templates/ و /tl_files/ یا زیرشاخه ها (همانند";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl42'] = "الگوی ایجاد شده).";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl50'] = "۵. اجرای InstallTool تایپولایت و وارد نمودن";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl51'] = "پوسته وب‌سایت.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt1'] = "ایجاد پوسته وب‌سایت";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt2'] = "ایجاد پوسته وب‌سایت ...";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt3'] = "پوسته تمام شد.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt4'] = "بستن پنجره";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt5'] = "لطفا فایل TXT را برای اطلاعات بیشتر بخوانید.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron1'] = "اضافه کردن AutoBackupDB به وظایف corn";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron2'] = "وظیفه پشتیبان‌گیری خودکار Corn غیرفعال شد";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron3'] = "وظیفه پشتیبان‌گیری خودکار Corn فعال شد";
 
?>
