<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/it/default.php 
 * 
 * Contao extension: BackupDB 1.2.0 stable 
 * Italian translation file 
 * 
 * Copyright : 2007-2009 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Hagen Klemp (do_while), http://www.softleister.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['backup_text'] = "Backup del database per il download";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_caption'] = "Avvia il backup";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_title'] = "Avvia il backup del database";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_text'] = "Salva la configurazione del sito web e crea un file da poter utilizzare con il tools di installazione";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_sqltxt'] = "   ";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_caption'] = "Crea un template del sito";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_button_title'] = "Crea un template del sito";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_files'] = "Nuovi files";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_module'] = "I seguenti moduli devono essere installati";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_none'] = "Nessuno";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_inst'] = "Installazione";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl10'] = "1. Installa la versione standard di Contao sul tuo spazio web.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl11'] = "(es. estrai il file zip e caricalo sul tuo spazio web)";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl12'] = "Non utilizzare lo strumento di installazione ora, verrà usato al punto 5";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl20'] = "2. Installare tutte le estensioni elencate.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl30'] = "3. Salva il template del sito nel percorso /templates/.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl40'] = "4. Salva tutti i file necessari al template del sito in";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl41'] = "/templates/ e /tl_files/.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl50'] = "5. Avvia lo strumento di installazione di Contao ed importa";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl51'] = "il file tempalte del sito.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt1'] = "Crea il file template del sito";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt2'] = "Creazione del file template....";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt3'] = "Creazione terminata";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt4'] = "Chiudi";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt5'] = "Si prega di leggere il file TXT per maggiori informazioni";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron1'] = "Aggiungi un AutoBackupDB ai processi schedulati";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron2'] = "Processo AutoBackupDB è DISABILITATO";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron3'] = "Processo AutoBackupDB è ATTIVO";
 
?>