<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/es/default.php 
 * 
 * Contao extension: BackupDB 1.2.0 stable 
 * Spanisch translation file 
 * 
 * Copyright : 2007-2010 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Hagen Klemp (do_while), http://www.softleister.de 
 * Translator: Klaus Bogotz (klabog) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['backup_text'] = "Copia del Banco de datos SQL de Contao como descarga";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_caption'] = "Arrancar copia de seguridad SQL";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_title'] = "Arranca la copia de seguridad SQL del banco de datos";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_text'] = "Guardar la configuración de la WEB y crear una plantilla para la herramienta de instalación [InstallTool (trad.)]";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_caption'] = "Crear plantilla de la WEB";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_button_title'] = "Arrancar la creación de la plantilla de la WEB";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_files'] = "Archivos nuevos:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_module'] = "Los siguientes módulos tienen que ser instalados:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_none'] = "ninguno";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_inst'] = "Instalación:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl10'] = "1. Instalar el paquete estándar de Contao en el dominio.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl11'] = "(p.e. extrayendo el ZIP y copiándolo por FTP al espacio WEB)";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl12'] = "No usar el InstallTool antes del punto 5!";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl20'] = "2. Instalación de todas las extensiones listadas.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl30'] = "3. Guardar esta plantilla de la WEB en /templates/.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl40'] = "4. Guardar todos los archivos necesarios para la plantilla en";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl41'] = "/templates/ y /tl_files/ o en sub-carpetas (igual que";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl42'] = "en la creación de la plantilla).";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl50'] = "5. Ejecutar la herramienta de instalación de Contao";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl51'] = "[InstallTool (trad.)] ahora e importa desde la plantilla de la WEB.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt1'] = "Crear plantilla de la WEB";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt2'] = "Creación de la plantilla de la WEB ...";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt3'] = "Plantilla creada.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt4'] = "Cerrar ventana";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt5'] = "Leer fichero TXT para más información.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron1'] = "Añadir AutoBackupDB a los cron jobs";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron2'] = "Cron job AutoBackupDB está DESACTIVADO";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron3'] = "Cron job AutoBackupDB está ACTIVADO";
 
?>
