<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/pl/default.php 
 * 
 * Contao extension: BackupDB 1.2.0 stable 
 * Polish translation file 
 * 
 * Copyright : 2007-2010 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Hagen Klemp (do_while), http://www.softleister.de 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['backup_text'] = "Utwórz i pobierz na dysk kopię zapasową Contao bazy danych SQL";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_caption'] = "Utwórz kopię zapasową bazy danych SQL";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_title'] = "Rozpoczęcie wykonania kopii zapasowej SQL";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_text'] = "Zachowaj bieżącą konfigurację i utwórz szablon strony dla Contao InstallTool";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_sqltxt'] = "   ";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_caption'] = "Utwórz szablon strony";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_button_title'] = "Rozpocznij tworzenie szablonu strony";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_files'] = "Nowe pliki:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_module'] = "Następujące moduły / rozszerzenia muszą zostać zainstalowane:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_none'] = "żadne";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_inst'] = "Instalacja:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl10'] = "1. Zainstaluj standardowy pakiet Contao w swojej domenie.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl11'] = "(np. wypakuj archiwum ZIP i wgraj pliki na serwer za pomocą klienta FTP)";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl12'] = "Nie uruchamiaj teraz narzędzia Contao InstallTool, dopiero w punkcie 5!";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl20'] = "2. Zainstaluj wszystkie wymienione wyżej moduły / rozszerzenia.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl30'] = "3. Zachowaj szablon strony w katalogu /templates/.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl40'] = "4. Zachowaj wszystkie pliki potrzebne do szablonu strony w katalogach";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl41'] = "/templates/ i /tl_files/ lub w podkatalogach (takich jak";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl42'] = "podczas tworzenia szablonu).";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl50'] = "5. Uruchom Contao InstallTool i wybierz szablon z";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl51'] = "the website-template.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt1'] = "utwórz szablon strony";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt2'] = "Tworzenie szablonu strony ...";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt3'] = "Szablon utworzony.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt4'] = "Zamknij okno";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt5'] = "Przeczytaj utworzony plik TXT aby uzyskać więcej informacji.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron1'] = "AutoBackupDB jako jedno z zadań crona Rejestracja";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron2'] = "AutoBackupDB jest zarejestrowany w INAKTIV Cron";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron3'] = "ACTIVE AutoBackupDB jest zarejestrowany w Cron";
 
?>