<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/ja/default.php 
 * 
 * Contao extension: BackupDB 3.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : 2007-2014 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Softleister (do_while), http://www.softleister.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['backup_text'] = "ContaoのデータベースのSQLバックアップをダウンロード";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_caption'] = "SQLバックアップを開始";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_title'] = "データベースのSQLバックアップを開始";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_text'] = "ウェブサイトの設定を保存して、インストールツールでインポートできるウェブサイトのテンプレートを作成";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_caption'] = "ウェブサイトのテンプレートを作成";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_button_title'] = "ウェブサイトのテンプレートの作成を開始";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_files'] = "新しいファイル:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_module'] = "以下のモジュールをインストールしていなければなりません:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_none'] = "なし";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_inst'] = "インストール:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl10'] = "1. ウェブのドメインに標準のContaoをインストールします。";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl11'] = "(例えば、ZIPファイルを展開してウェブの場所にFTPでアップロードします。)";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl12'] = "この時点ではインストールツールを使用しません。5.の段階で実行します!";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl20'] = "2. リストに載った機能拡張をインストールします。";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl30'] = "3. このウェブサイトのテンプレートを /templates/ のパスにアップロードして置きます。";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl40'] = "4. ウェブサイトのテンプレートに必要なすべてのファイルを";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl41'] = "/templates/ や /tl_files/ や、そのサブディレクトリのパスに";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl42'] = "(テンプレートを作成したときのよう)置きます。";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl50'] = "5. ここでContaoのインストールツールを実行して、ウェブサイトの";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl51'] = "テンプレートからインポートしてください。";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt1'] = "ウェブサイトのテンプレートを作成";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt2'] = "ウェブサイトのテンプレートを作成 ...";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt3'] = "テンプレートを完了。";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt4'] = "ウィンドウを閉じる";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt5'] = "TXTファイルを読んでください。";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron1'] = "データベースの自動バックアップをcronのジョブに追加";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron2'] = "cronのジョブ: データベースの自動バックアップは無効";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron3'] = "cronのジョブ: データベースの自動バックアップは有効";
 
?>
