<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/ja/modules.php 
 * 
 * Contao extension: BackupDB 3.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : 2007-2014 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Softleister (do_while), http://www.softleister.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['BackupDB']['0'] = "データベースをバックアップ";
$GLOBALS['TL_LANG']['MOD']['BackupDB']['1'] = "データベースのバックアップをダウンロード";
 
?>
