<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/ja/tl_settings.php 
 * 
 * Contao extension: BackupDB 3.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : 2007-2014 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Softleister (do_while), http://www.softleister.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['backupdb_saveddb']['0'] = "ウェブサイトのテンプレートのデータテーブル";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_saveddb']['1'] = "ウェブサイトのテンプレートに含めるテーブルのプリフィックスやテーブルをコンマで区切ったリストで入力してください。Contaoのコアのすべてのテーブルは<em>tl_</em>で始まっています。機能拡張のカタログのテーブルは<em>cat_</em>で始まっているでしょう。";
$GLOBALS['TL_LANG']['tl_settings']['AutoBackupCount']['0'] = "データベースの自動バックアップでバックアップする数";
$GLOBALS['TL_LANG']['tl_settings']['AutoBackupCount']['1'] = "データベースの自動バックアップで作成するバックアップの数で初期値は3です。最新のバックアップは常に<em>AutoBackupDB-1.sql</em>というファイルとなります。";
$GLOBALS['TL_LANG']['tl_settings']['WsTemplatePath']['0'] = "ウェブサイトのテンプレートの別のパス";
$GLOBALS['TL_LANG']['tl_settings']['WsTemplatePath']['1'] = "パスの初期値は<em>templates</em>です。ウェブサイトのテンプレートを保持する異なるディレクトリを指定できます。";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_blacklist']['0'] = "バックアップの除外リスト";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_blacklist']['1'] = "データベースの<strong>バックアップしない</strong>テーブルの名前をコンマで区切ったリストです。例えば、以下のテーブルは復元に絶対に必要ではありません: <em>tl_lock</em>, <em>tl_log</em>, <em>tl_search</em>, <em>tl_search_index</em>, <em>tl_session</em>, <em>tl_undo</em>, <em>tl_version</em>";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_sendmail']['0'] = "自動バックアップ後に電子メールで通知";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_sendmail']['1'] = "バックアップの完了後に管理者に電子メールを送信しします。";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_attmail']['0'] = "自動バックアップのファイルを付加";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_attmail']['1'] = "通知の電子メールにバックアップのファイルを付加します。";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_zip']['0'] = "バックアップを圧縮";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_zip']['1'] = "バックアップをzipアーカイブとして圧縮できます。";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_legend'] = "BackupDBの設定";
 
?>
