<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/ru/default.php 
 * 
 * Contao extension: BackupDB 1.4.0 rc1 
 * Russian translation file 
 * 
 * Copyright : 2007-2011 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Hagen Klemp (do_while), http://www.softleister.de 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['backup_text'] = "Создание и загрузка резервной копии SQL базы данных Contao";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_caption'] = "Запуск резервного копирования";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_title'] = "Запуск резервного копирования SQL базы данных";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_text'] = "Сохранение конфигурации веб-сайта и создание шаблона для установщика Contao";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_caption'] = "Создать шаблон веб-сайта";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_button_title'] = "Запуск и создание шаблона веб-сайта";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_files'] = "Новые файлы:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_module'] = "Внимание! Следующие модули должны быть установлены:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_none'] = "ничего";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_inst'] = "Установка:";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl10'] = "1. Установите стандартный пакет Contao в домене.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl11'] = "(напр. извлеките ZIP архив и выгрузите содержимое по FTP на ваш веб-сайт)";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl12'] = "Не используйте установщик Contao прямо сейчас, дойдите до 5 шага!";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl20'] = "2. Установите все перечисленные расширения.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl30'] = "3. Сохраните этот шаблон веб-сайта в папку /templates/ сайта.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl40'] = "4. Сохраните все файлы, необходимые для шаблона веб-сайта в папку";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl41'] = "/templates/ и /tl_files/, а также в подпапки (точно так же,";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl42'] = "как в создаваемом шаблоне).";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl50'] = "5. Запустите установщик Contao и импортируйте";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl51'] = "шаблон веб-сайта.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt1'] = "создание шаблона веб-сайта";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt2'] = "Создание шаблона веб-сайта...";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt3'] = "Шаблон создан.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt4'] = "Закрыть окно";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt5'] = "Пожалуйста, прочтите TXT файл для получения дополнительной информации.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron1'] = "Добавить AutoBackupDB к заданиям планировщика";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron2'] = "Задание AutoBackupDB отключено!";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron3'] = "Задание AutoBackupDB включено!";
 
?>
