<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/ru/tl_settings.php 
 * 
 * Contao extension: BackupDB 1.4.0 rc1 
 * Russian translation file 
 * 
 * Copyright : 2007-2011 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Hagen Klemp (do_while), http://www.softleister.de 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['backupdb_saveddb']['0'] = "Таблицы данных шаблона веб-сайта";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_saveddb']['1'] = "Введите разделенный запятыми список префиксов таблиц или таблиц для включения в шаблон веб-сайта. Все таблицы ядра Contao  начинаются с <em>tl_</em>, каталог таблицы может иметь префикс <em>cat_</em>.";
$GLOBALS['TL_LANG']['tl_settings']['AutoBackupCount']['0'] = "Количество резервных копий AutoBackupDB";
$GLOBALS['TL_LANG']['tl_settings']['AutoBackupCount']['1'] = "Количество файлов резервных копий, созданных AutoBackupDB, значение по умолчанию — 3. Самая последняя копия всегда находится в файле <em>AutoBackupDB-1.sql</em>.";
$GLOBALS['TL_LANG']['tl_settings']['WsTemplatePath']['0'] = "Альтернативный путь для шаблонов сайта";
$GLOBALS['TL_LANG']['tl_settings']['WsTemplatePath']['1'] = "Путь по умолчанию - <em>templates</em>. Вы можете указать другую папку, в которой хранятся шаблоны веб-сайта.";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_legend'] = "Настройки BackupDB";
 
?>
