<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/fr/default.php 
 * 
 * Contao extension: BackupDB 1.4.1 stable 
 * French translation file 
 * 
 * Copyright : 2007-2011 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Hagen Klemp (do_while), http://www.softleister.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['backup_text'] = "Sauvegarde de la base de données de Contao";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_caption'] = "Démarrer la sauvegarde";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['button_title'] = "Lance la sauvegarde de la base de données";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_text'] = "Sauvegarder la configuration du site et créer un modèle de site";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_sqltxt'] = "   ";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_caption'] = "Créer un modèle de site";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_button_title'] = "Lance la création d'un modèle de site";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_files'] = "Nouveaux fichiers :";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_module'] = "Les modules suivant doivent être installés :";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_none'] = "aucun";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_inst'] = "Installation :";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl10'] = "1. Effectuer une installation standard de Contao sur votre domaine.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl11'] = "(ex. extraire le fichier .zip et envoyer par FTP sur votre serveur web)";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl12'] = "Ne pas utiliser l'outil d'installation de Contao maintenant, seulement à l'étape 5 !";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl20'] = "2. Installation de toutes les extentions énumérées.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl30'] = "3. Envoi par FTP du modèle de site dans le répertoire /templates/.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl40'] = "4. Enregistrer tous les fichiers nécessaires pour le site modèle";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl41'] = "dans le répertoire /templates/ et /tl_files/ ou sous-répertoires";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl42'] = "(Exactement comme dans le site ayant servi à la création du modèle).";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl50'] = "5. Lancer l'outil d'installation de Contao et importer";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_anl51'] = "le modèle de site.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt1'] = "Créer un modèle de site";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt2'] = "Création du modèle de site...";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt3'] = "Modèle créé.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt4'] = "Fermer la fenêtre";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_txt5'] = "Veuillez lire le fichier .txt pour plus d'informations.";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron1'] = "Ajouter AutoBackupDB aux tâches cron";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron2'] = "La tâche cron AutoBackupDB est INACTIVE";
$GLOBALS['TL_LANG']['MSC']['tl_backupdb']['ws_template_cron3'] = "La tâche cron AutoBackupDB est ACTIVE";
 
?>
