<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/fr/modules.php 
 * 
 * Contao extension: BackupDB 1.4.1 stable 
 * French translation file 
 * 
 * Copyright : 2007-2011 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Hagen Klemp (do_while), http://www.softleister.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['BackupDB']['0'] = "Sauvegarde de la base";
$GLOBALS['TL_LANG']['MOD']['BackupDB']['1'] = "Ce module permet d'avoir, en téléchargement, une copie de sauvegarde de la base de donnée.";
 
?>
