<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/fr/tl_settings.php 
 * 
 * Contao extension: BackupDB 1.4.1 stable 
 * French translation file 
 * 
 * Copyright : 2007-2011 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Hagen Klemp (do_while), http://www.softleister.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['backupdb_legend'] = "Paramètres de BackupDB";
 
?>
